# module_events.py
# NEXO / ZYRA — LOGÍSTICA ASIA
# EVENTOS PROPIOS DEL MÓDULO
# PASIVO | CANÓNICO

MODULE_EVENTS = {
    "SHIPMENT_CREATED",
    "SHIPMENT_UPDATED",
    "TRACKING_UPDATED",
    "CUSTOMS_CLEARED",
    "DELIVERY_CONFIRMED",
    "LOGISTICS_ALERT"
}